apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: app-podinfo
  annotations:
    metadata.weave.works/dashboard.app_url: http://${LOADBALANCER:=localhost}:9898
spec:
  interval: 2m
  chart:
    spec:
      chart: ./charts/podinfo
      sourceRef:
        kind: GitRepository
        name: "podinfo-gitrepository"
      version: '>=0.0.3'
  values:
    service:
      type: LoadBalancer
    ui:
      message: "Hi, this message is from the Helm values for ephemeral environments"
      color: ""
